### ISSUE TITLE
Checks not pulling in 'enhances' packages leading to check NOTEs

### ISSUE THREAD

**Issue by shikokuchuo** [r-universe-org/help#468] opened 2024-08-19 09:17 UTC
Great job with the new checks summary! It made me aware of this issue.

See e.g. https://github.com/r-universe/shikokuchuo/actions/runs/10448884345/job/28930238949#step:5:220

I believe 'enhances' packages should be treated the same as 'suggests'.

**Comment by jeroen** [comment] 2024-08-19 10:59
Is there an easy way to do this? We just use `install.packages(depends=TRUE)` afaik. From the `install.packages` docs:

> TRUE means to use c("Depends", "Imports", "LinkingTo", "Suggests") for pkgs and c("Depends", "Imports", "LinkingTo") for added dependencies: this installs all the packages needed to run pkgs, their examples, tests and vignettes (if the package author specified them correctly).

Is there an envvar to disable this NOTE?

PS, this sort of things is the reason I don't like to obsess about `CMD check` in r-universe. It doesn't add to the quality of packages to try to work around all these silly notes.

**Comment by jeroen** [comment] 2024-08-19 11:49
I tried that but that recursively installs all suggests from all other suggests. So we end up with hundreds of dependencies.

**Comment by jeroen** [comment] 2024-08-19 11:53
We have an open issue to switch to pak: https://github.com/r-universe-org/help/issues/393. But sadly that is blocked by a bug in pak that makes it hang if there are multiple overlapping package repositories.

**Comment by shikokuchuo** [comment] 2024-08-19 11:58
> I tried that but that recursively installs all suggests from all other suggests. So we end up with thousands of dependencies.

Wow, that's crazy. I just confirmed - it's due to what `knitr` is pulling in. But `TRUE` doesn't download recursively, so a documentation bug for base R it seems.

Yeah, I'd go with `pak` as soon as it's possible.

**Comment by jeroen** [comment] 2024-08-19 12:02
> so a documentation bug for base R it seems.

I don't think so, it says explicitly : 

```
TRUE means to use c("Depends", "Imports", "LinkingTo", "Suggests") for pkgs and c("Depends", "Imports", "LinkingTo") for added dependencies
```

**Comment by shikokuchuo** [comment] 2024-08-19 12:03
Agree. I didn't read it carefully enough.

**Comment by jeroen** [comment] 2024-08-19 12:05
What is the purpose for your `Enhances: promises` by the way? Where is this used?

**Comment by shikokuchuo** [comment] 2024-08-19 12:06
`nanonext` provides an S3 method for `promises`. I think this is the archetypal purpose for 'enhances'.

**Comment by shikokuchuo** [comment] 2024-08-19 12:13
From what I see, it doesn't look worthwhile to do anything in particular for 'enhances', but just to note that this is solvable once the move to `pak` is complete.

**Comment by jeroen** [comment] 2024-08-20 09:44
Closing this because for now this works as intended. When we switch to pak, hopefully we can use `dependencies="all"`. As a workaround if you are really bothered by the NOTE, maybe you can add the package to both`Suggests` and `Enhances`.

**Closed** 2024-08-21 10:27 UTC

**Comment by jeroen** [comment] 2024-08-21 10:30
I found a way to fix it after all :) Should work now.

**Comment by shikokuchuo** [comment] 2024-08-21 10:38
Thanks for keeping this in mind! I see the checks are now clean: https://shikokuchuo.r-universe.dev/nanonext
